### ISSUE TITLE
Paper with code

### ISSUE THREAD

**Issue by shi27feng** [DirtyHarryLYL/Transformer-in-Vision#1]
Hi @DirtyHarryLYL,

Thank you for posting our paper on your list, the code can be found at:
("STAR: Sparse Transformer-based Action Recognition")
https://github.com/imj2185/STAR.

Best regards,

**Comment by DirtyHarryLYL** [comment]
Thanks! The repo link was added.

**Comment by taokong** [comment]
iBOT: Image BERT Pre-Training with Online Tokenizer
 code here https://github.com/bytedance/ibot
