### ISSUE TITLE
(ICCV'23) VL-PET: Vision-and-Language Parameter-Efficient Tuning via Granularity Control

### ISSUE THREAD

**Issue by HenryHZY** [DirtyHarryLYL/Transformer-in-Vision#6]
Hi, you might be interested in our ICCV'23 paper.
paper: https://arxiv.org/abs/2308.09804
code: https://github.com/HenryHZY/VL-PET
project page: https://henryhzy.github.io/VL-PET
baselines: LoRA, VL-Adapter, LST and etc.

Thank you! :)

**Comment by DirtyHarryLYL** [comment]
Thanks, updated!
